### ISSUE TITLE
load Large/base class dataset

### ISSUE THREAD

**Issue by fikry102** [LiBromine/few-shot#1]
When I tried to run the train_act.py, there was something wrong.
It seems that "base_feature.npy" and "base_label.txt" are missing.
Could you please upload these two files?

**Comment by Bingrui-Li** [comment]
I have uploaded the "base_label.txt" with the supplemental "base_label_meaning.txt", and you can download the "base_feature.npy" from this link, https://cloud.tsinghua.edu.cn/f/93d4ee8d801c4f48afe9/?dl=1, :)
